version: "3.7"

services:
  app:
    container_name: gateway_service
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
      - API_PORT=${API_PORT}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
    build:
      context: .
      dockerfile: "./docker/${ENVIRONMENT}/dockerfile"
    volumes:
      - .:/app
      - /app/node_modules

